name: authserver
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

dependencies:
  args: ^2.4.0
  crypt: ^4.3.1
  dart_jsonwebtoken: ^2.12.2
  google_sign_in: ^6.2.1
  googleapis_auth: ^1.6.0
  mailer: ^6.1.0
  mockito: ^5.4.4
  mongo_dart: ^0.9.4
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^1.1.0
  lints: ^2.1.0
  test: ^1.24.0
