name: Dart Test

on:
  push:
    

jobs:
  test:
      runs-on: ubuntu-latest

      steps:
        - uses: dart-lang/setup-dart@v1
        - uses: actions/checkout@v3
        
        - name: Install dependencies
          run: dart pub get
                 
        - name:  
          run: dart run bin/server.dart &
          shell: bash

        - name: Run Test 
          run : dart test test/server_test.dart
            
         
 

        

        
     
    
 
  