name: Dart Test

on:
  push:
    

jobs:
  test:
      runs-on: ubuntu-latest

      steps:
        - uses: dart-lang/setup-dart@v1
        - uses: actions/checkout@v3
       
        - name: Build  Container 
          run:  docker build  -t authserver .             
        - name:  
          run: docker run authserver &
          shell: bash

        - name: Install dependencies
          run: dart pub get

        - name: Run Test 
          run : dart test test/server_test.dart
            
         
 

        

        
     
    
 
  